### ISSUE TITLE
Moon position

### ISSUE THREAD

**Issue by charleslemaire0** [MarScaper/ephemeris#2]
at Lat 0° and Long 0°
time 01.01.2019 at 01:01:01 UT

the given moon position by ephemeris is RA 14.83431000 Dec -10.96680600
or 14h50m03.516s and 10°58'0".502

from carte du ciel I get these values
Coordinates: Apparent Topocentric
Apparent RA: 14h51m48.31s DE:-10°49'49.5"
Mean of the date RA: 14h51m49.23s DE:-10°49'57.1"
Mean J2000 RA: 14h50m47.81s DE:-10°45'17.7"

Please could you check the ephemeris computation for the moon.

For the other solar system object the position is accurate

**Comment by kbahey** [comment]
I have the same problem. 

The moon is 47 arc minutes away from where it should be. 

Other solar system objects are accurate.

**Comment by MarScaper** [comment]
After discussion with Charles, the eq coordinates are expressed in geocentric. It's not an issue with planets cause the parallax is very small but with the moon It's an issue. I'm working on topocentric conversion. It should be ok quickly.

**Comment by kbahey** [comment]
This is good news. Looking forward to it.

**Comment by MarScaper** [comment]
I've just committed last changes. It should be ok.

**Comment by kbahey** [comment]
There is a problem when using the ephemeris now. 

The struct in ELP2000.hpp needs to change from char to int, otherwise, it would not compile on ESP32.

Here is the patch:
```

diff --git a/ELP2000.hpp b/ELP2000.hpp
index 981a250..de92fa5 100644
--- a/ELP2000.hpp
+++ b/ELP2000.hpp
@@ -29,11 +29,11 @@
 
 struct ELP2000Coefficient
 {
-    char Ec;
-    char D;
-    char M;
-    char Mp;
-    char F;
+    int Ec;
+    int D;
+    int M;
+    int Mp;
+    int F;
 };
```

After this, the SHC code compiles, but there is an error message: 'Set Target Failed' for all solar system objects, not just the moon.

Howard Dutton, author of OnStep, had a fork of the Ephemeris, and it does work, except for the moon offset issue.

**Comment by MarScaper** [comment]
Compilation with ESP32 do not implement char? int is a bad choice cause it increases the memory footprint. ELP2000 coefficient can be set as int8_t instead. I'll change It to resolve your compatiblity issue.

'Set Target Failed'? I don't know what your talking about. This message do not come from Ephemeris library.

**Comment by kbahey** [comment]
Yes, this message is not from the Ephemeris itself, rather from the [SHC code](https://github.com/hjd1964/OnStep/tree/Alpha/addons/St4Serial/SmartHandController), which is part of OnStep. 

Howard had his [own fork of the Ephemeris](https://github.com/hjd1964/ephemeris) which we used for the SHC code. We thought we can switch back to your code base, but there seems to be some issues in it with the SHC. No idea what. Howard switched back to his fork, since there seems to be significant differences.

**Comment by MarScaper** [comment]
I've committed the char->int8_t change. Let me know if you find the issue with SHC.

**Comment by MarScaper** [comment]
Charles,  Moon position on Arduino with you test is now: R.A:  14h51m46s.41 Dec: -10d49'56".58
Much better.

**Comment by charleslemaire0** [comment]
this is an excellent achievement, Thanks! If I could I would have add an other star ;)

**Comment by charleslemaire0** [comment]
tested it works

**Comment by kbahey** [comment]
Sebastien, 

We finally integrated it in OnStep's SHC. The issue was that we did not do the call to setLocationOnEarth() before doing the solarSystemObjectAtDateTime call. That is why it was saying 'Set Target failed'.

Fixed it, and now the accuracy for the moon is very good. 

Some offset on nearby planets (Venus/Mars), but not really a problem. 

Details on test results [here](https://groups.io/g/onstep/message/9024) and [here](https://groups.io/g/onstep/message/9051).

**Comment by MarScaper** [comment]
Great! For sure, Ephemeris library needs to know "where" and "when" to do the job... ;)
Nice to see Ephemeris working great on other projects than mine!

I can go back to my toys... :p
![IMG_4079](https://user-images.githubusercontent.com/25328509/55278960-48a88b00-5313-11e9-8038-881e42e57ba7.jpg)
